import "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import "../css/app.css";
import "./bannerBusqueda";
import "./bootstrap";
import "./repositoriosPagination";
import "./mobileMenu";
import "./carpetasNav"
import "./renderPdfsPage"
import "./filtros";
